### ISSUE TITLE
Update Person, Delete Person

### ISSUE THREAD

**Issue by gokulkrshna** [mohammed-Emad/add_faces_to_svm_class#2]
Interesting approach of incremental learning, similarly how would you support updating person images with new ones, or deleting a person? How do you update the model with these changes?

**Comment by mohammed-Emad** [comment]
Hi
As for retraining data for the same person or deleting data for one person, they are disabled features that were not of interest at the time, so this form simply will refuse to enter the names of repeat people.
But the solutions to both problems are simple
First, adding data to the same person with the same name is not a problem.
You will need to skip one part of the code [here](https://github.com/mohammed-Emad/add_faces_to_svm_class/blob/b817b224cadc3bd0a62144e1f9401a8734da977b/my_clasifiy.py#L162)
```python3
     if name in class_old:     #find
             name_deleted.append(name) 
             image_del +=len(cls.image_paths)
```
and It is the part that prevents training for the same people again


The second problem: is to delete someone’s data from the data
---
This problem does not include the code clear treatment for it, so you will have to write text yourself
The code task you will write is to use emb_old, labels_old, class_old
First, find out the face order in the class_old name list
Then use the values to delete the name and its features from the three menus: emb_old, labels_old, class_old

The code will be similar to the following
```python3
class_old  = np.array(['a','b','c','d','f','g'])
labels_old = np.array([1,5,3,5,5,1,5,5,8])
emb_old    = np.array([1,2,3,4,5,4,7,9,2]) 

del_names = ['b','g']
len_c = class_old
for del_name in del_names:
    for name in range(len(len_c)):
        if  del_name == len_c[name]:
            index = np.where(class_old==del_name)
            class_old = np.delete(class_old, index)

            index = np.where(labels_old.astype(int) == name)
            labels_old = np.delete(labels_old, index) 
            emb_old = np.delete(emb_old, index) 

print(class_old)
print(labels_old)
print(emb_old)
```

output
-
```shell
['a' 'c' 'd' 'f']
[3 8]
[3 2]
```

Good luck..
